# Generated by Django 4.1.3 on 2023-10-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=500, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("is_mailed", models.BooleanField(default=False)),
            ],
        ),
    ]
