# Generated by Django 4.1.3 on 2023-10-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="l_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
