# Generated by Django 4.1.3 on 2023-10-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_client_address_phone_client_l_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_mailed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
