# Generated by Django 4.1.3 on 2023-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_client_is_mailed"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="last_mail_date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
